version: '2'
services:
  db:
    image: postgres:9.4
    ports:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=sobe_app_development

  web:
    environment:
      - RAILS_SERVE_STATIC_FILES=true
      - RAILS_ENV=development
      - RACK_ENV=development
      - DB_NAME=sobe_app_development
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_HOST=db
      - DB_PORT=5432
    links:
      - db
    build: .
    volumes:
      - .:/myapp
    entrypoint: [bin/entry]
    command: /opt/rh/rh-ruby22/root/usr/bin/bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    depends_on:
      - db
